---
title: "HW#10"
author: "Lily Shapiro"
date: "4/7/2020"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---
1. 
```{r}
# ----------------------------------------
# FUNCTION count_zeros
# description: counts the number of zeroes in a numeric vector
# inputs: vector of size 500 with random numbers
# outputs: number of zeros in vector
##########################################
count_zeros <- function(my_vec=round(runif(500))) {
counter <- 0
for (i in seq_along(my_vec)){
     if (my_vec[i]==0){
       counter <- counter + 1
     }
}
return(counter)
} # end of count_zeros
#-----------------------------------------
count_zeros()
```
2. 
```{r}
# ----------------------------------------
# FUNCTION count_zeros_subs
# description: counts zeroes of a function using subsetting
# inputs: vector of size 500 with random numbers
# outputs: count of zeroes in vector
##########################################
count_zeros_subs <- function(my_vec_sub=round(runif(500))) {
  
 s <- sum(my_vec_sub==0)
  return(s)
} # end of count_zeros_subs
#-----------------------------------------
count_zeros_subs()
```

3. 
```{r}
# ----------------------------------------
# FUNCTION matrix_vals
# description: Calculates matrix values derived from row and column values 
# inputs: integers representing row and column numbers for matrix
# outputs: matrix of row and column dimensions with elements in matrix = row # x column #
##########################################
matrix_vals <- function(nrow=5,ncol=6) {
  
  m <- matrix(NA,nrow=nrow,ncol=ncol)
    for (i in 1:nrow(m)){
    for (j in 1:ncol(m)){
      m[i,j] <- i*j
    }
  }
  print(m)
}

#-----------------------------------------
matrix_vals()
```

#4. 
```{r}
library(TeachingDemos)
library(ggplot2)
set.seed(2000)
o_color <- rnorm(n=62, mean=9.3, sd=1.3)
lat <- runif(62, 0, 60)
y <- o_color +(lat*.07)

# ----------------------------------------
# FUNCTION read.data
# description: Reads in previously defined data
# inputs: opisthosoma color and latitude 
# outputs: 3 column data frame: ID, opisthosoma and latitude 
##########################################
read.data <- function(z=NULL) {
  
  if (is.null(z)){
o_color <- rnorm(n=62, mean=9.3, sd=1.3)
lat <- runif(62, 0, 60)
y <- o_color +(lat*.07)
      x_obs <- o_color
      y_obs <- y 
      z <- data.frame(ID=seq_along(x_obs), 
                       x_obs, 
                       y_obs)
      return(z)
    } else {
df <- read.table(file=z,
                 header=TRUE,
                 stringsAsFactors = FALSE) }
return(df)

} # end of read.data
#-----------------------------------------
read.data()
# ----------------------------------------
# FUNCTION calc.regression  
# description: calulations metric pre-randomization 
# inputs: 3 column data frame (ID, o_color, y)
# outputs: slope from regression
##########################################
calc.regression <- function(z=NULL) {
  if (is.null(z)){
    x_obs <- o_color
    y_obs <- y
    z <- data.frame(ID=seq_along(x_obs), 
                     x_obs, 
                     y_obs)}
  . <- lm(z[,3]~z[,2])
  . <- summary(.)
  . <- .$coefficients[2]
  slope <- . 
  return(slope)

} # end of calc.anova
#-----------------------------------------
calc.regression()
# ----------------------------------------
# FUNCTION shuffle.data
# description: randomizes data for test
# inputs: 3 column data frame (ID, opisthosoma c, y)
# outputs: 3 column data frame
##########################################
shuffle.data <- function(z=NULL) {
  if (is.null(z)){
    x_obs <- o_color  
    y_obs <- y
    z <- data.frame(ID=seq_along(x_obs), 
                     x_obs, 
                     y_obs)}
z[,3] <- sample(z[,3])


return(z)

} # end of shuffle.data
#-----------------------------------------
shuffle.data()

# ----------------------------------------
# FUNCTION get.pval
# description: calculate p value from simulation  
# inputs: list of observed metric and vector of simulated metrics 
# outputs: lower, and upper tail probability value
##########################################
get_pval <- function(z=NULL) {
  
    if(is.null(z)){
      z <- list(rnorm(1), rnorm(1000)) }
      p_lower <- mean(z[[2]]<=z[[1]])
      p_upper <- mean(z[[2]]>=z[[1]])

return(c(pL=p_lower,pU=p_upper))
} # end of get.pval
#-----------------------------------------
get_pval()

# ----------------------------------------
# FUNCTION plot_ran_test
# description: create a ggplot of histogram of simulated values
# inputs: list of observed metric and vector simulated metrics
# outputs: saved ggplot graph
##########################################
plot_ran_test <- function(z=NULL) {
  
              if(is.null(z)){
                z <- list(rnorm(1), rnorm(1000))}
  df <- data.frame(ID=seq_along(z[[2]]), sim_x=z[[2]])
  p1 <- ggplot(data=df, mapping=aes(x=sim_x))
  p1 + geom_histogram(mapping = aes(fill=I("pink"), color=I("black"))) +
    geom_vline(aes(xintercept=z[[1]], col="blue"))

} # end of plot_ran_test
#-----------------------------------------
plot_ran_test()

#Analysis

n_sim <- 3000 
x_sim <- rep(NA, n_sim)
df <- read.data()
x_obs <- calc.regression(df)

for (i in seq_len(n_sim)) {
  x_sim[i] <- calc.regression(shuffle.data(df))
} # run simulation
slopes <- list(x_obs, x_sim)
get_pval(slopes)
plot_ran_test(slopes)

```
#5. 
```{r}
model <- lm(o_color ~ y, data=df)
summary(model)
#P values are significantly different between randomized and non-randomized runs


```

